title: '96'
description: 'Website for personal projects.'

header_pages:
  - index.md

footer: '<span style="float:right">ƒ</span><a href="https://github.com/charadev96">github</a> <a href="https://www.youtube.com/@charadev96">youtube</a>'

style: dark
listen_for_clients_preferred_style: false

remote_theme: b2a3e8/jekyll-theme-console
